### ISSUE TITLE
Whitespace in navbar bug

### ISSUE THREAD

**Issue by MarkusJohansen** [MarkusJohansen/dagens-ord#101]
![image](https://github.com/user-attachments/assets/6d1fd21c-1f2f-4e40-9131-aa050411318d)

**Comment by henrikmw** [comment]
How can i recreate this?

**Comment by MarkusJohansen** [comment]
I am using firefox on a macbook air 2018 model. It is a problem that it cant be recreated 🧐

**Comment by henrikmw** [comment]
Yeah I couldn't recreate it in firefox either, weird

**Comment by henrikmw** [comment]
I think this is closed with the screen width and screen height commit i pushed to main?
