### ISSUE TITLE
Adminpanel

### ISSUE THREAD

**Issue by MarkusJohansen** [MarkusJohansen/dagens-ord#72]
Fast and simple way for administrators to accept or deny new suggestions. Should support editing typos in suggestions and existing suggestions. 

We should create a milestone for this issue and break it down into several subissues.

**Comment by henrikmw** [comment]
Create and deploy backoffice esque dashboard?

**Comment by MarkusJohansen** [comment]
wouldve been nice :)

**Comment by MarkusJohansen** [comment]
We will need authentication for admins and login functionality from navbar as well to do this.

**Comment by MarkusJohansen** [comment]
#119
