### ISSUE TITLE
About the project page and navbar rework

### ISSUE THREAD

**Issue by MarkusJohansen** [MarkusJohansen/dagens-ord#96]
Instead of button style navigation to a single page, lets add an "about"-page and rework the navigation to look like actual links. Keep in mind that the design should support a "teite ord"-switch extension in the future, at least for desktop... (we should have this functionality for mobile users as well; it is horrible practice to deny mobile users the same services). navbar rework for mobile in another PR?

**Comment by henrikmw** [comment]
Are you thinking about a solution with tabs instead of the "Bidra" button?

**Comment by MarkusJohansen** [comment]
> Are you thinking about a solution with tabs instead of the "Bidra" button?

Sure, you can call it tabs. I was thinking more like standard navbar "links". Yes i dont want the button there, if we have several pages; it is not conventional design to use buttons for navigation this way.

![image](https://github.com/user-attachments/assets/5c78f69a-4c86-4d49-a40c-ac1b2f2d33e1)
